### ISSUE TITLE
苏老师，想问一下，您之后会出什么其他的课程吗？或者关于某一个点深入的讲解（专栏）？

### ISSUE THREAD

**Issue by WjF1991** [DevOpsLakes/devopslakes.github.io#3]
视频看了很多遍了，也练了很多了，看第一遍，即使上手练习，也不知所以然，很多专业术语没有听说过，之前也没有详细研究过某一个工具（SVN、VSS），看第二遍然后练习的过程中思考了工具功能设计的思路，现在用起来顺畅多了！说这些就是想说有一个导师的感觉非常好！

**Comment by unaheidi** [comment]
我想有合适的机会，我还会继续写、继续讲的。
最近在深入了解 GitLab 的 CI，摸索需要花很多的时间。
大家有问题可以在这里交流，我时不时会上来看看的。

谢谢支持！
